title: "Anisia Popescu"
author: "Anisia Popescu"
description: "LISN, Université Paris Saclay"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true       # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {file: "README.md", title: "Projects"}
  - {file: "publications.md", title: "Publications"} 
  - {file: "teaching.md", title: "Teaching"}
  - {file: "test.md", title: "test"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:anisiapopescu358@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/anisiapopescu"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
